    sources:
      - MontaguSlab.glyphs
    outputDir: "../../fonts"
    ttDir: "../../fonts/ttf"
    # buildOTF: False
    familyName: Montagu Slab
    axisOrder:
      - opsz
      - wght
    stat:
      - name: Optical size
        tag: opsz
        values:
        - name: 16pt
          value: 16
        - name: 144pt
          value: 144
      - name: Weight
        tag: wght
        values:
        - name: Thin
          value: 100
        - name: ExtraLight
          value: 200
        - name: Light
          value: 300
        - name: Regular
          value: 400
          linkedValue: 700
          flags: 2
        - name: Medium
          value: 500
        - name: SemiBold
          value: 600
        - name: Bold
          value: 700
    # instances:
    #   MontaguSlab[opsz,wght].ttf:
    #   - familyName: "Montagu Slab 144pt"
    #     styleName: "Thin"
    #     coordinates:
    #       opsz: 144
    #       wght: 100
    #   - familyName: "Montagu Slab 144pt"
    #     styleName: "ExtraLight"
    #     coordinates:
    #       opsz: 144
    #       wght: 200
    #   - familyName: "Montagu Slab 144pt"
    #     styleName: "Light"
    #     coordinates:
    #       opsz: 144
    #       wght: 300
    #   - familyName: "Montagu Slab 144pt"
    #     styleName: "Regular"
    #     coordinates:
    #       opsz: 144
    #       wght: 400
    #   - familyName: "Montagu Slab 144pt"
    #     styleName: "Medium"
    #     coordinates:
    #       opsz: 144
    #       wght: 500
    #   - familyName: "Montagu Slab 144pt"
    #     styleName: "SemiBold"
    #     coordinates:
    #       opsz: 144
    #       wght: 600
    #   - familyName: "Montagu Slab 144pt"
    #     styleName: "Bold"
    #     coordinates:
    #       opsz: 144
    #       wght: 700
    #   - familyName: "Montagu Slab 16pt"
    #     styleName: "Thin"
    #     coordinates:
    #       opsz: 16
    #       wght: 100
    #   - familyName: "Montagu Slab 16pt"
    #     styleName: "ExtraLight"
    #     coordinates:
    #       opsz: 16
    #       wght: 200
    #   - familyName: "Montagu Slab 16pt"
    #     styleName: "Light"
    #     coordinates:
    #       opsz: 16
    #       wght: 300
    #   - familyName: "Montagu Slab 16pt"
    #     styleName: "Regular"
    #     coordinates:
    #       opsz: 16
    #       wght: 400
    #   - familyName: "Montagu Slab 16pt"
    #     styleName: "Medium"
    #     coordinates:
    #       opsz: 16
    #       wght: 500
    #   - familyName: "Montagu Slab 16pt"
    #     styleName: "SemiBold"
    #     coordinates:
    #       opsz: 16
    #       wght: 600
    #   - familyName: "Montagu Slab 16pt"
    #     styleName: "Bold"
    #     coordinates:
    #       opsz: 16
    #       wght: 700